services:
  - type: web
    name: wedding-photo-server
    env: docker
    dockerfilePath: server/Dockerfile
    dockerContext: server
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_OPTIONS
        value: --openssl-legacy-provider
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: DRIVE_FOLDER_ID
        sync: false
      - key: ADMIN_SECRET
        sync: false
      - key: CLIENT_URL
        sync: false
